### ISSUE TITLE
How to run reports?

### ISSUE THREAD

**Issue by jgbarah** [grimoirelab/reports#4]
In the `README.md` I read, as an example of the command for running `reports` (slightly edited):

```$ 
bin/report -g --data-sources git gerrit its mls -u <elastic_url> -s 2015-04-01 -e 2017-04-01 \
  -d project_data -i quarter
```

I guess I can figure out all the options except for `-d project_data`. Do you happen to have an example of that `project_data` file, or maybe a description of the format?

**Comment by acs** [comment]
According to the help:

```
(acs@dellx) (master $% u=) ~/devel/reports $ bin/report -h
...
-d DATA_DIR, --data-dir DATA_DIR
                        Directory to store the data results

```

this param  "--data-dir" points to the directory in which to store all data (csv and eps files mainly with metrics) that will be used to create the report PDF file.

**Comment by alpgarcia** [comment]
I've proposed an update adding usage information to README file.

If you feel we need something else, like data file examples, let me know to modify my PR.

**Comment by acs** [comment]
PR merged. Closing this issue.

**Comment by jgbarah** [comment]
OK, fair enough, thanks.
